### PR TITLE
add evergreen and wyvtils

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
im waiting on the next evergreenhud update to release, at which point i'll update my repos and copy all my changes from there to here

**Comment by Wyvest** [comment]
> im waiting on the next evergreenhud update to release, at which point i'll update my repos and copy all my changes from there to here

should i close this pr then?

**Comment by proudmuslim-dev** [comment]
@MicrocontrollersDev Should I merge this?

**Comment by proudmuslim-dev** [comment]
Merging, let me know if I should revert

**Comment by Wyvest** [comment]
the wyvtils repo changed but it'll redirect anyways

**Comment by proudmuslim-dev** [comment]
> the wyvtils repo changed but it'll redirect anyways

Feel free to open another PR fixing that

**Pull request merged**
